get http://localhost:8080/blog/api/users
###
get http://localhost:8080/blog/api/user/3bbe460f-b43b-46af-84f9-e61b7be62476

### 

post http://localhost:8080/blog/api/user/register
Content-Type: application/json 

{
   "fullName": "John Doe",
   "username": "john023",
   "email": "john02@email.com",
   "password": "123"
   
}

### 
# Posts
get http://localhost:8080/posts
###
get http://localhost:8080/post/1

### 

post http://localhost:8080/post
Content-Type: application/json 

{
   "title": "Learn Javascript first of learning NodeJs",
    "description": "NodeJs is a main javascript run time.",
   "content": "...",
    "userId": "3bbe460f-b43b-46af-84f9-e61b7be62476",
   
}